CREATE DATABASE IF NOT EXISTS chatdb;
use chatdb;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255)
        CHARACTER SET utf8,
    UNIQUE(login)

);
CREATE TABLE IF NOT EXISTS room_users (
    roomId INT NOT NULL,
    userId INT NOT NULL
);
CREATE TABLE IF NOT EXISTS rooms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tag VARCHAR(255)NOT NULL,
    name VARCHAR(255)
        CHARACTER SET utf8,
    UNIQUE(tag)

);
CREATE TABLE IF NOT EXISTS room_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    roomId INT NOT NULL,
    userId INT NOT NULL,
    time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    body VARCHAR(2048)
        CHARACTER SET utf8
);