CREATE DATABASE IF NOT EXISTS chatdb;
use chatdb;
CREATE TABLE IF NOT EXISTS users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL

);
CREATE TABLE IF NOT EXISTS room_users (
    ROOM_ID INT NOT NULL,
    USER_ID INT NOT NULL
);
CREATE TABLE IF NOT EXISTS room_messages (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    BODY TEXT 

);